### ISSUE TITLE
Similar project with fewer brackets

### ISSUE THREAD

**Issue by jiyinyiyong** [TheTrung/lrb#1]
Just invite you to see my project on running Ruby in Lisp-like syntax, while mine comes with much fewer brackets. Are you interested in such syntax?
https://github.com/Cirru/sepal.rb

I may learn your project by the way.

**Comment by TheTrung** [comment]
I have thought about that idea previously, quite nice though :))

My attempt project actually is just transform Ruby a bit, and it may not get further anymore.
